@startuml
'https://plantuml.com/class-diagram

abstract class Drink{
    String description;
    float price;
    setPrice()
    setDes()
    getDes()
    abstract cost()
}
abstract class Coffee extends Drink{
    cost()
}
class ShortBlack extends Coffee{
    setPrice()
    setDes()
}
class LongBlack extends Coffee{
    setPrice()
    setDes()
}
class Espresso extends Coffee{
    setPrice()
    setDes()
}

abstract class Decorator extends Drink{
    Drink component;
    getDes()
}

class Chocolate extends Decorator{
    setPrice()
    setDes()
}

class Milk extends Decorator{
    setPrice()
    setDes()
}

Decorator *--->Drink

@enduml