@startuml
'https://plantuml.com/class-diagram

abstract class InputStream implements Closeable{}
class FilterInputStream extends InputStream{
    protected volatile InputStream in;
}
class FileInputStream extends InputStream{

}
class ByteArrayInputSteam extends InputStream{

}
class DataInputStream extends FilterInputStream implements DataInput{
}

class BufferedInputStream extends FilterInputStream implements DataInput{
}


FilterInputStream *---> InputStream




@enduml