@startuml
'https://plantuml.com/class-diagram


class Voltage220V{}

interface IAdapter5V{}

class VoltageAdapter extends Voltage220V implements IAdapter5V{
}

class Phone{
    IAdapter5V adapter5v;
}

Phone o... IAdapter5V

Client ...>Phone
Client ...>VoltageAdapter


@enduml