@startuml
'https://plantuml.com/class-diagram

interface IAdapter{
    op1();
    op2();
    op3();
}

abstract class AbsAdapter implements IAdapter{
    op1();
    op2();
    op3();
}

class Adapter extends AbsAdapter{
    op1();
}



@enduml